ame: Publish Docker image
#on:
#  release:
#    types: [published]
on:
  push:
    branches: master
jobs:
  push_to_registry:
    name: Push Docker images to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Get commit SHA
        id: get_sha
        run: echo "::set-env name=COMMIT_SHA::$(echo ${GITHUB_SHA:10})"
      - name: Set ENV variables
        run: for v in `cat .env` ; do echo "::set-env name=${v%%=*}::${v##*=}" ; done
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.alpine
          build-args: S6_OVERLAY_VERSION,COMMIT_SHA
          push: true
