name: Docker Image CI

on:
  push:
    branches: [ ubuntu-latest ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag azmo/base:ubuntu-latest --tag azmo/base:ubuntu-latest-$(date +%s)
