---
name: Publish Docker image
#on:
#  release:
#    types: [published]
on:
  push:
    branches: master
jobs:
  push_to_registry:
    name: Push Docker images to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get commit SHA
        id: get_sha
        run: echo "COMMIT_SHA=${GITHUB_SHA:10}" >> $GITHUB_ENV
      - name: Set ENV variables from supplied .env file
        run: cat .env >> $GITHUB_ENV
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.alpine
          build-args:
            - S6_OVERLAY_VERSION=${{ env.S6_OVERLAY_VERSION }}
            - COMMIT_SHA=${{ env.COMMIT_SHA }}
          tags: azmo/base:alpine,azmo/base:alpine-${{env.COMMIT_SHA}}
